(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var l=aa(this),ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ca={a:!0},u={};try{u.__proto__=ca;n=u.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var x=m;
function y(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(x)x(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ga=b.prototype}var da=this||self;function A(a,b){return a.x*b.x+a.y*b.y}function B(a,b){return C(b,A(a,b))}function C(a,b){return E(a.x*b,a.y*b)}function E(a,b){return{x:a,y:void 0!==b?b:a}};function F(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a}function G(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a};function H(a,b){return window.setTimeout(a,b)};function I(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d}function ea(a,b){b=void 0===b?null:b;var c=void 0===c?null:c;H(function(){var d=I("autoplayended",a,b);c&&c(d)},1)}function fa(a,b){function c(d){a.removeEventListener("attached",c);b(d)}a.addEventListener("attached",c)}function ha(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=H(function(){c=null;b&&(a(),b=!1)},250))}};var K=["-ms-","-moz-","-webkit-",""];function L(a,b,c){var d=void 0===d?!1:d;for(var e,k,g=0;g<K.length;g++)e=K[g]+b,k=(d?K[g]:"")+c,a.style.setProperty(e,k)};function M(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")}function ia(a){if(M(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&M(a))return a;return null}function N(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)}function ja(a){return(a=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"")?a.split(",").map(function(b){return b.trim()}):[]};/*

 SPDX-License-Identifier: Apache-2.0
*/
function P(a,b){this.g=b===Q?a:""}P.prototype.toString=function(){return this.g.toString()};P.prototype.l=!0;P.prototype.h=function(){return this.g.toString()};var ka=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,Q={};function R(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)if(!/^[\s\xa0]*$/.test(a[c])){var d=b,e=d.push;var k=a[c];k=k.trim();k=window.Enabler?window.Enabler.getUrl(k):k;var g=document.createElement("gwd-image");g.setAttribute("source",k);e.call(d,g)}}return b}function S(a,b){for(var c=0;c<a.length;c++){var d=a[c];"gwd-image"==d.tagName.toLowerCase()&&(null!=b?d.setAttribute("scaling",b):d.removeAttribute("scaling"))}}function la(a,b){return"left"==a||"backwards"==a?-b:b}
function ma(a,b){return(a%b+b)%b};function na(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval}function oa(a){this.g=a;this.h=null;this.l=!1}
function T(a,b,c,d){c=void 0===c?"forwards":c;if(a.g.frameCount&&null==a.h){if(d){var e=Math.floor(b/d);b=d}else e=a.g.frameCount,b/=e;var k=[],g=na(a.g);d=g;for(var h=0;h<e;h++)0<h&&(d=ma(d+la(c,1),a.g.frameCount)),k.push(d);c=function(){if(k.length){var q=k.shift();a.l=!0;a.g.goToFrame(q+1);a.l=!1;I("frameautoplayed",a.g,{id:q+1})}else a.stop(!0),a.g.goToFrame(g+1)};a.h=window.setInterval(c,b);setTimeout(c,1)}}
oa.prototype.stop=function(a){a=void 0===a?!1:a;!this.l&&this.h&&(window.clearInterval(this.h),ea(this.g,{completed:a}),this.h=null)};var pa=["pause-front-media","resume-next-media"];function U(){var a=HTMLElement.call(this)||this;a.frames=[];a.i=null;a.j=0;a.s=1;a.K=new oa(a);a.qa=!1;a.ra=!1;return a}y(U,HTMLElement);f=U.prototype;f.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.qa="true"==c;break;case "resume-next-media":this.ra="true"==c}};f.gwdIsLoaded=function(){return!0};f.gwdLoad=function(){};
f.goToFrame=function(a,b){this.stopRotation();0!=this.j&&(a>this.j?a=this.j:1>a&&(a=1),this.ma(a,b))};f.ma=function(a){this.i=a-1};function qa(a,b,c,d){if(null!=a.i){var e=a.s;e=ma(a.i+la(b,void 0===e?1:e),a.s*Math.ceil(a.j/a.s));!d&&("forwards"==b&&e<a.i||"backwards"==b&&e>a.i)||a.goToFrame(e+1,c)}}f.goBackwards=function(a,b){qa(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};f.goForwards=function(a,b){qa(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};
f.rotateOnce=function(a,b){T(this.K,void 0===a?0:a,b)};f.stopRotation=function(){this.K.stop()};f.getFrame=function(a){if(0!=this.j)return this.frames[a-1]};f.ta=function(a){var b=a.length;a=a.splice(0,b);for(var c=0;c<b;c++){var d=a[c];"frameshown"==d?I(d,this,{id:this.currentIndex}):I(d,this)}};
l.Object.defineProperties(U.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.j?this.i+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.s}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.j}}});l.Object.defineProperties(U,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return pa}}});var ra="images scaling frame-width frame-height frame-snap-interval num-frames-to-display offset start-frame swipe-axis pause-front-media resume-next-media autoplay-duration autoplay-step-interval disable-gesture exit-urls has-navigation navigation-highlight navigation-thumbnails swipe-threshold-ratio swipe-committed-threshold-ratio transition-duration".split(" ");
function V(){var a=U.call(this)||this;a.S=!1;a.g=null;a.T=null;a.O=!1;a.B=E(0);a.C=null;a.o=!1;a.l=null;a.da=a.Aa.bind(a);a.fa=a.Ca.bind(a);a.ba=a.ya.bind(a);a.ca=a.za.bind(a);a.ea=a.Ba.bind(a);a.X=a.va.bind(a);a.pa=a.Fa.bind(a);a.oa=a.Ea.bind(a);a.na=a.Da.bind(a);a.Z=a.wa.bind(a);a.ga=a.xa.bind(a);a.ia=ha(a.sa.bind(a));a.N=I.bind(null,"firstinteraction",a);a.U=!1;a.H=[];a.A=a.ta.bind(a,a.H);a.V=0;a.W=0;a.L=0;a.la=0;a.ka=0;a.R=1;a.M=[];a.P=0;a.ja=1;a.ua=.7;a.I=0;a.J=!1;a.D=E(0);a.v=E(0);a.m=null;
a.aa=-1;a.u=-1;a.Y=[];a.F=E(-1,-1);a.h=E(1,0);a.G=!1;return a}y(V,U);f=V.prototype;
f.connectedCallback=function(){if(!this.G){if(this.O=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);var a=document.createElement("gwd-gesture");a.className="gesture";this.C=a;this.G=!0}a=this.C;a.addEventListener("pointerover",this.fa,!1);a.addEventListener("pointerout",this.da,!1);a.addEventListener("pointermove",this.ba,!1);a.addEventListener("track",this.pa,!1);a.addEventListener("trackend",this.oa,!1);a.addEventListener("tap",this.na,!1);this.addEventListener("frametap",
this.Z,!1);this.addEventListener("swipefinished",this.ha,!1);this.addEventListener("transitionend",this.A,!1);this.addEventListener("webkitTransitionEnd",this.A,!1);this.gwdIsLoaded()||((a=ia(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());window.addEventListener("resize",this.ia,!1)};
f.disconnectedCallback=function(){window.removeEventListener("resize",this.ia,!1);var a=this.C;a.removeEventListener("pointerover",this.fa,!1);a.removeEventListener("pointerout",this.da,!1);a.removeEventListener("pointermove",this.ba,!1);a.removeEventListener("track",this.pa,!1);a.removeEventListener("trackend",this.oa,!1);a.removeEventListener("tap",this.na,!1);this.removeEventListener("frametap",this.Z,!1);this.removeEventListener("swipefinished",this.ha,!1);this.removeEventListener("transitionend",
this.A);this.removeEventListener("webkitTransitionEnd",this.A)};
f.attributeChangedCallback=function(a,b,c,d){if(this.G)switch(a){case "images":this.frames=R(this.getAttribute("images"));sa(this);W(this);break;case "scaling":S(this.frames,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":ta(this);W(this);break;case "transition-duration":case "exit-urls":case "autoplay-duration":case "autoplay-step-interval":X(this);break;case "frame-width":case "frame-height":case "frame-snap-interval":case "num-frames-to-display":case "swipe-axis":X(this);W(this);
break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":W(this);break;default:U.prototype.attributeChangedCallback.call(this,a,b,c,d)}else U.prototype.attributeChangedCallback.call(this,a,b,c,d)};
function X(a){var b=F(a,"num-frames-to-display",1),c=F(a,"frame-snap-interval",1),d=F(a,"transition-duration",600),e=F(a,"frame-width",-1),k=F(a,"frame-height",-1),g=G(a,"autoplay-duration",3E3),h=G(a,"autoplay-step-interval",0);a.F.x=e;a.F.y=k;e="y"===a.getAttribute("swipe-axis");a.h=E(e?0:1,e?1:0);-1!=A(a.F,a.h)?b=-1:0<b&&c>b&&(c=b);a.Y=ja(a);a.u=b;a.s=c;a.L=d;a.V=g;a.W=h}
function W(a){var b=E(a.clientWidth,a.clientHeight);a.m&&(b.y-=36,a.T.style.height=b.y+"px");var c=G(a,"swipe-threshold-ratio",.1),d=G(a,"swipe-committed-threshold-ratio",.5),e=a.h,k=a.u,g=a.F,h=a.frames,q=parseInt(a.getAttribute("offset"),10);isNaN(q)&&(q=0);q=C(e,q);g=E(-1==g.x?b.x:g.x,-1==g.y?b.y:g.y);if(a.hasAttribute("offset")){a:{var r=g.x,p=g.y,z=!0;if(a.hasAttribute("clamp-frame-size-to-image")){var v=a.getAttribute("clamp-frame-size-to-image");"true"==v?z=!0:"false"==v&&(z=!1)}if(z)if(v=
a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain",z="contain"==v,!z&&"none"!=v||0==r||0==p)h={width:r,height:p};else{for(var J=v=-1,xa=h.length,O=0;O<xa;O++){var t=h[O];if("img"!=t.tagName.toLowerCase()&&"gwd-image"!=t.tagName.toLowerCase()){h={width:r,height:p};break a}var w=t.assetWidth?t.assetWidth:t.naturalWidth,D=t.assetHeight?t.assetHeight:t.naturalHeight;0<w&&0<D&&(z?w/D<r/p?(t=w/D*p,w=p):(t=r,w=D/w*r):(t=w,w=D),v=Math.max(v,t),J=Math.max(J,w))}h={width:-1!=v?Math.min(r,v):r,height:-1!=
J?Math.min(p,J):p}}else h={width:r,height:p}}1==e.x?g.x=h.width:g.y=h.height}1<k&&(h=C(e,k-1),h=E(h.x*q.x,h.y*q.y),h=B(E((b.x-h.x)/k,(b.y-h.y)/k),e),h.x&&(g.x=h.x),h.y&&(g.y=h.y));h=2<k?1+Math.ceil(k/2-1):1;r=parseInt(a.getAttribute("start-frame"),10);isNaN(r)&&(r=h);h=B(E(g.x+q.x,g.y+q.y),e);p=1+2*Math.floor((A(e,b)-A(e,g))/(2*A(e,h)));if(1>p||!isFinite(p))p=1;b=E((b.x-g.x)/2,(b.y-g.y)/2);0<k&&0==k%2&&(e=B(E(g.x+q.x,g.y+q.y),e),b.x-=.5*e.x,b.y-=.5*e.y,p+=1);e=a.hasAttribute("disable-gesture");a.v=
g;a.D=b;a.R=p;a.I=A(h,a.h);a.ja=r;a.o=e;a.la=A(a.v,a.h)*c;a.ka=A(a.v,a.h)*d;c=B(a.D,E(a.h.y,a.h.x));for(e=0;e<a.j;e++)d=a.frames[e].style,d.left=c.x+"px",d.top=c.y+"px",d.width=a.v.x+"px",d.height=a.v.y+"px",c.x+=h.x,c.y+=h.y;a.B=E(0);a.g&&(Y(a,0,0,0),c=B(a.D,a.h),a.g.style.left=c.x+"px",a.g.style.top=c.y+"px");a.i=null;a.goToFrame(a.ja,"none")}f.gwdIsLoaded=function(){return this.S};
f.gwdLoad=function(){if(!this.S&&!this.g){if(this.O)var a=R(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;sa(this)}};f.goBackwards=function(a,b){return U.prototype.goBackwards.call(this,a,void 0===b?!1:b)};f.goForwards=function(a,b){return U.prototype.goForwards.call(this,a,void 0===b?!1:b)};
f.ma=function(a,b){var c=this.s;var d=this.j;var e=this.u;--a;a=a-a%c+Math.floor((c-1)/2);0>a?a=0:a>=d&&(a=d-1);1<e&&(c=a-Math.floor((e-1)/2),e=c+e-1,0>c&&e<d-1&&(a+=Math.min(-c,d-e-1)),e>=d&&0<c&&(a-=Math.min(e-d+1,c)));d=a;if(null!=this.i&&this.i!=d){if(this.qa)for(e=Array.prototype.slice.call(this.frames[this.i].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),a=0;a<e.length;a++)c=e[a],c.pause&&c.pause();if(this.ra)for(e=Array.prototype.slice.call(this.frames[d].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),
a=0;a<e.length;a++)c=e[a],c.play&&c.play()}e=this.i;this.i=d;d=C(this.h,-this.I*this.i);Y(this,"none"!=b?this.L:0,d.x,d.y);this.B=d;if(this.P)for(b=Math.floor((this.R-1)/2),d=0;d<this.R;d++)if(a=this.i-b+d,!(0>a||a>=this.j||this.M[a]||(this.M[a]=!0,--this.P))){this.H.push("allframesviewed");break}e!=this.i&&(ua(this,this.i+1),this.H.push("frameshown"),this.H.push("swipefinished"));this.U||this.A()};
function Y(a,b,c,d){a.U=0<b;L(a.g,"transition","transform "+b+"ms");L(a.g,"transform","translate3d("+c+"px,"+d+"px,0)")}
function sa(a){if(a.G){for(;a.firstChild;)a.removeChild(a.firstChild);a.m=null;a.g&&(a.g.removeEventListener("pageload",a.ga,!1),a.g.removeEventListener("mouseover",a.ea,!0),a.g.removeEventListener("mouseout",a.ca,!0),a.g.removeEventListener("click",a.X,!0));for(var b=a.frames,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d];L(e,"user-select","none");e.classList.add("frame");c.appendChild(e)}fa(c,c.gwdLoad.bind(c));a.g=c;a.g.className="container";a.g.addEventListener("pageload",
a.ga,!1);a.g.addEventListener("mouseover",a.ea,!0);a.g.addEventListener("mouseout",a.ca,!0);a.g.addEventListener("click",a.X,!0);S(a.frames,a.getAttribute("scaling"));a.j=a.frames.length;b=a.ownerDocument.createElement("div");a.T=b;b.className="matte";b.appendChild(a.g);a.appendChild(a.T);a.appendChild(a.C)}}f.ha=function(){L(this.g,"transition","transform 0ms")};
f.xa=function(a){a.target===this.g&&(this.S=!0,this.P=this.j,this.M=[],X(this),ta(this),W(this),I("allframesloaded",this),this.hasAttribute("autoplay")&&T(this.K,this.V,"forwards",this.W),I("ready",this))};f.sa=function(){X(this);W(this)};f.rotateOnce=function(a,b){T(this.K,a||this.L,b)};function va(a,b){var c=a.j;if(c){var d=a.i;b=wa(a,b);a.goToFrame(b+1);d!=b&&(0==b?I("reachleftend",a):b==c-1&&I("reachrightend",a))}}
function ta(a){var b=a.hasAttribute("has-navigation"),c=!!a.m;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.m=a.ownerDocument.createElement("gwd-gallerynavigation"),a.m.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.m)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.m),a.m=null);a.m&&(N(a,"navigation-highlight",a.m,"highlight"),N(a,"navigation-thumbnails",a.m,"use-thumbnails"))}
function wa(a,b){var c=a.i;Math.abs(b)>a.la&&(c=0>b?c+a.s:c-a.s);0>c?c=0:c>=a.j&&(c=a.j-1);return c}function ua(a,b){a.aa!=b&&(a.aa=b,I("frameactivated",a,{id:b||a.currentIndex}))}f.Fa=function(a){if(!this.o&&(this.N&&(this.N(),this.N=null),!this.J))if(this.stopRotation(),a=A(E(a.dx,a.dy),this.h),ua(this,wa(this,a)+1),Math.abs(a)>this.ka)va(this,a),this.J=!0;else{var b=a;if(0<a&&0===this.i||0>a&&this.i===this.j-1)b-=a*this.ua;Y(this,0,this.B.x+this.h.x*b,this.B.y+this.h.y*b)}};
f.Ea=function(a){this.o||(this.J?this.J=!1:va(this,A(E(a.dx,a.dy),this.h)))};function Z(a,b){var c=a.getBoundingClientRect();b=E(b.clientX-c.left,b.clientY-c.top);c=a.h;var d=E(c.y,c.x);c=A(d,b);var e=A(d,a.D);d=A(d,a.v);if(c<e||c>e+d)return null;c=a.h;b=A(c,b)-A(c,a.B)-A(c,a.D);c=Math.floor(b/a.I);return 0>c||c>=a.j||b%a.I>A(a.h,a.v)?null:c}
f.Da=function(a){if(!this.o){this.stopRotation();var b=this.C;var c=this.g;var d=a.clientX,e=a.clientY,k=b.style["pointer-events"];b.style["pointer-events"]="none";d=c.ownerDocument.elementFromPoint(d,e);b.style["pointer-events"]=k;if(b=d)if(c.contains&&1==d.nodeType)b=c==d||c.contains(d);else if("undefined"!=typeof c.compareDocumentPosition)b=c==d||!!(c.compareDocumentPosition(d)&16);else{for(b=d;b&&c!=b;)b=b.parentNode;b=b==c}c=b?d:null;(b=!c)||(b=a.clientX,k=a.clientY,d=!1,"gwd-taparea"===c.tagName.toLowerCase()&&
(d=c.ownerDocument.createEvent("Event"),d.initEvent("action",!0,!0),d.clientX=b,d.clientY=k,d=!c.dispatchEvent(d)),b=!d);b&&(a=Z(this,a),null!=a&&I("frametap",this,{element:this.frames[a],id:a+1}))}};
f.wa=function(a){(a=a.detail&&a.detail.id)&&(a=this.Y[a-1])&&!I("frameexit",this,{url:a}).detail.handled&&(a instanceof P||a instanceof P||(a="object"==typeof a&&a.l?a.h():String(a),ka.test(a)||(a="about:invalid#zClosurez"),a=new P(a,Q)),da.open(a instanceof P&&a.constructor===P?a.g:"type_error:SafeUrl",""))};f.Aa=function(){this.o||null==this.l||(I("framemouseout",this,{element:this.frames[this.l],id:1+this.l}),this.l=null)};
f.Ca=function(a){this.o||(a=Z(this,a),a!=this.l&&(null!=this.l&&I("framemouseout",this,{element:this.frames[this.l],id:1+this.l}),null!=a&&I("framemouseover",this,{element:this.frames[a],id:1+a}),this.l=a))};f.ya=function(a){this.o||(a=Z(this,a),a!=this.l&&(null!=this.l&&I("framemouseout",this,{element:this.frames[this.l],id:1+this.l}),null!=a&&I("framemouseover",this,{element:this.frames[a],id:1+a}),this.l=a))};
f.Ba=function(a){this.o&&a.target.classList.contains("frame")&&I("framemouseover",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};f.za=function(a){this.o&&a.target.classList.contains("frame")&&I("framemouseout",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};f.va=function(a){this.o&&a.target.classList.contains("frame")&&I("frametap",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};
l.Object.defineProperties(V.prototype,{firstVisibleFrameIndex:{configurable:!0,enumerable:!0,get:function(){var a=0<this.u&&0<this.j&&null!=this.i?Math.max(1,this.i-Math.floor((this.u-1)/2)+1):void 0;return a}},lastVisibleFrameIndex:{configurable:!0,enumerable:!0,get:function(){var a=0<this.u&&0<this.j&&null!=this.i?Math.min(this.j,this.i-Math.floor((this.u-1)/2)+this.u):void 0;return a}}});l.Object.defineProperties(V,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ra}}});
customElements.define("gwd-swipegallery",V);}).call(this);
